//go:build linux && t04_rehearsal

package updater

// These compile-time paths exist only in the isolated T04 acceptance build.
// The control-plane Server is deliberately outside the local Server-residue
// namespace so removing a test Agent cannot touch the Server fixture.
const (
	DefaultSocket                 = "/run/404-probe-t04-agent/agent-updater.sock"
	updaterStateDirectory         = "/var/lib/404-probe-t04-agent-updater"
	liveAgentBinary               = "/usr/local/lib/404-probe-t04-agent/404-probe-agent"
	stagedAgentBinary             = "/usr/local/lib/404-probe-t04-agent/.404-probe-agent.candidate"
	previousAgentBinary           = "/usr/local/lib/404-probe-t04-agent/.404-probe-agent.previous"
	bootstrapAgentBinary          = "/usr/local/lib/404-probe-t04-agent/.404-probe-agent.bootstrap"
	agentServiceName              = "404-probe-t04-agent.service"
	agentUnitPath                 = "/etc/systemd/system/404-probe-t04-agent.service"
	agentUpdaterUnitPath          = "/etc/systemd/system/404-probe-t04-agent-updater.service"
	agentUpdaterSocketDirectory   = "/run/404-probe-t04-agent"
	serviceUserName               = "404-probe-t04-agent"
	serverUnitPath                = "/etc/systemd/system/404-probe-t04-local-server.service"
	serverBinaryPath              = "/usr/local/lib/404-probe-t04-local-server/404-probe-server"
	serverDatabasePath            = "/var/lib/404-probe-t04-local-server/404-probe.db"
	serverEnvironmentPath         = "/etc/404-probe-t04-agent/server.env"
	serverControlTokenPath        = "/etc/404-probe-t04-agent/control.token"
	serverWebPasswordHashPath     = "/etc/404-probe-t04-agent/web-password.hash"
	serverUpgradeDirectory        = "/var/lib/404-probe-t04-local-server-upgrade"
	serverUpgradeLockDirectory    = "/run/404-probe-t04-local-server-upgrade"
	serverUpgradeLockPath         = "/run/404-probe-t04-local-server-upgrade/server.lock"
	serverUpgradeCandidatePath    = "/usr/local/lib/404-probe-t04-local-server/.404-probe-server.candidate"
	serverUpgradePreviousPath     = "/usr/local/lib/404-probe-t04-local-server/.404-probe-server.previous"
	serverUpgradeHelperCandidate  = "/usr/local/lib/404-probe-t04-agent/404-probe-install.candidate"
	agentEnvironmentPath          = "/etc/404-probe-t04-agent/agent.env"
	agentEpochPath                = "/var/lib/404-probe-t04-agent/agent.epoch"
	agentEpochLockPath            = "/var/lib/404-probe-t04-agent/agent.epoch.lock"
	agentSecurityAcksPath         = "/var/lib/404-probe-t04-agent/agent.security-acks.json"
	selectorOrderPath             = "/etc/404-probe-t04-agent/selector-order.json"
	installHelperPath             = "/usr/local/lib/404-probe-t04-agent/404-probe-install"
	agentConfigDirectory          = "/etc/404-probe-t04-agent"
	agentStateDirectory           = "/var/lib/404-probe-t04-agent"
	securityStateDirectory        = "/var/lib/404-probe-t04-agent-security"
	securityServiceUnitPath       = "/etc/systemd/system/404-probe-t04-agent-security.service"
	securityTimerUnitPath         = "/etc/systemd/system/404-probe-t04-agent-security.timer"
	removalStateDirectory         = "/var/lib/404-probe-t04-agent-updater/removal"
	removalRequestPath            = "/var/lib/404-probe-t04-agent-updater/removal/request.json"
	removalFinishedMarker         = "/var/lib/404-probe-t04-agent-updater/removal/agent-uninstalled"
	removalWorkerBinary           = "/usr/local/lib/404-probe-t04-agent/.404-probe-agent-removal-worker"
	removalWorkerUnitPath         = "/etc/systemd/system/404-probe-t04-agent-removal.service"
	removalWorkerUnitName         = "404-probe-t04-agent-removal.service"
	removalFinalizerUnitPath      = "/etc/systemd/system/404-probe-t04-agent-removal-finalize.service"
	removalFinalizerUnitName      = "404-probe-t04-agent-removal-finalize.service"
	removalHelperContract         = "REMOVAL_STATE_DIRECTORY"
	removalAccountHelperContract  = "finalize-agent-removal-account"
	removalWorkerWritablePaths    = "/var/lib/404-probe-t04-agent-updater /etc/systemd/system"
	removalFinalizerWritablePaths = "/etc /var/lib /run /usr/local/lib"
)
