//go:build linux && !role_rehearsal && !t04_rehearsal

package updater

const (
	DefaultSocket                 = "/run/404-probe/agent-updater.sock"
	updaterStateDirectory         = "/var/lib/404-probe-updater"
	liveAgentBinary               = "/usr/local/bin/404-probe-agent"
	stagedAgentBinary             = "/usr/local/bin/.404-probe-agent.candidate"
	previousAgentBinary           = "/usr/local/bin/.404-probe-agent.previous"
	bootstrapAgentBinary          = "/usr/local/bin/.404-probe-agent.bootstrap"
	agentServiceName              = "404-probe-agent.service"
	agentUnitPath                 = "/etc/systemd/system/404-probe-agent.service"
	agentUpdaterUnitPath          = "/etc/systemd/system/404-probe-agent-updater.service"
	agentUpdaterSocketDirectory   = "/run/404-probe"
	serviceUserName               = "404-probe"
	serverUnitPath                = "/etc/systemd/system/404-probe-server.service"
	serverBinaryPath              = "/usr/local/bin/404-probe-server"
	serverDatabasePath            = "/var/lib/404-probe/404-probe.db"
	serverEnvironmentPath         = "/etc/404-probe/server.env"
	serverControlTokenPath        = "/etc/404-probe/control.token"
	serverWebPasswordHashPath     = "/etc/404-probe/web-password.hash"
	serverUpgradeDirectory        = "/var/lib/404-probe-upgrade"
	serverUpgradeLockDirectory    = "/run/404-probe-upgrade"
	serverUpgradeLockPath         = "/run/404-probe-upgrade/server.lock"
	serverUpgradeCandidatePath    = "/usr/local/bin/.404-probe-server.candidate"
	serverUpgradePreviousPath     = "/usr/local/bin/.404-probe-server.previous"
	serverUpgradeHelperCandidate  = "/usr/local/sbin/404-probe-install.candidate"
	agentEnvironmentPath          = "/etc/404-probe/agent.env"
	agentEpochPath                = "/var/lib/404-probe/agent.epoch"
	agentEpochLockPath            = "/var/lib/404-probe/agent.epoch.lock"
	agentSecurityAcksPath         = "/var/lib/404-probe/agent.security-acks.json"
	selectorOrderPath             = "/etc/404-probe/selector-order.json"
	installHelperPath             = "/usr/local/sbin/404-probe-install"
	agentConfigDirectory          = "/etc/404-probe"
	agentStateDirectory           = "/var/lib/404-probe"
	securityStateDirectory        = "/var/lib/404-probe-security"
	securityServiceUnitPath       = "/etc/systemd/system/404-probe-security-collect.service"
	securityTimerUnitPath         = "/etc/systemd/system/404-probe-security-collect.timer"
	removalStateDirectory         = "/var/lib/404-probe-updater/removal"
	removalRequestPath            = "/var/lib/404-probe-updater/removal/request.json"
	removalFinishedMarker         = "/var/lib/404-probe-updater/removal/agent-uninstalled"
	removalWorkerBinary           = "/usr/local/bin/.404-probe-agent-removal-worker"
	removalWorkerUnitPath         = "/etc/systemd/system/404-probe-agent-removal.service"
	removalWorkerUnitName         = "404-probe-agent-removal.service"
	removalFinalizerUnitPath      = "/etc/systemd/system/404-probe-agent-removal-finalize.service"
	removalFinalizerUnitName      = "404-probe-agent-removal-finalize.service"
	removalHelperContract         = "REMOVAL_STATE_DIRECTORY"
	removalAccountHelperContract  = "finalize-agent-removal-account"
	removalWorkerWritablePaths    = "/var/lib/404-probe-updater /etc/systemd/system"
	removalFinalizerWritablePaths = "/etc /var/lib /run /usr/local/bin /usr/local/sbin"
)
