//go:build linux && role_rehearsal

package updater

// These constants exist only in the test-only role_rehearsal build. They are
// deliberately compile-time mappings; no remote or runtime input can alter
// the updater, account, helper, unit, or removal-state paths.
const (
	DefaultSocket                 = "/run/404-probe-role-rehearsal/agent-updater.sock"
	updaterStateDirectory         = "/var/lib/404-probe-role-rehearsal-updater"
	liveAgentBinary               = "/usr/local/lib/404-probe-role-rehearsal/404-probe-agent"
	stagedAgentBinary             = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-agent.candidate"
	previousAgentBinary           = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-agent.previous"
	bootstrapAgentBinary          = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-agent.bootstrap"
	agentServiceName              = "404-probe-role-agent-rehearsal.service"
	agentUnitPath                 = "/etc/systemd/system/404-probe-role-agent-rehearsal.service"
	agentUpdaterUnitPath          = "/etc/systemd/system/404-probe-role-agent-updater-rehearsal.service"
	agentUpdaterSocketDirectory   = "/run/404-probe-role-rehearsal"
	serviceUserName               = "404-probe-role-rehearsal"
	serverUnitPath                = "/etc/systemd/system/404-probe-role-server-rehearsal.service"
	serverBinaryPath              = "/usr/local/lib/404-probe-role-rehearsal/404-probe-server"
	serverDatabasePath            = "/var/lib/404-probe-role-rehearsal/404-probe.db"
	serverEnvironmentPath         = "/etc/404-probe-role-rehearsal/server.env"
	serverControlTokenPath        = "/etc/404-probe-role-rehearsal/control.token"
	serverWebPasswordHashPath     = "/etc/404-probe-role-rehearsal/web-password.hash"
	serverUpgradeDirectory        = "/var/lib/404-probe-role-rehearsal-upgrade"
	serverUpgradeLockDirectory    = "/run/404-probe-role-rehearsal-upgrade"
	serverUpgradeLockPath         = "/run/404-probe-role-rehearsal-upgrade/server.lock"
	serverUpgradeCandidatePath    = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-server.candidate"
	serverUpgradePreviousPath     = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-server.previous"
	serverUpgradeHelperCandidate  = "/usr/local/lib/404-probe-role-rehearsal/404-probe-install.candidate"
	agentEnvironmentPath          = "/etc/404-probe-role-rehearsal/agent.env"
	agentEpochPath                = "/var/lib/404-probe-role-rehearsal/agent.epoch"
	agentEpochLockPath            = "/var/lib/404-probe-role-rehearsal/agent.epoch.lock"
	agentSecurityAcksPath         = "/var/lib/404-probe-role-rehearsal/agent.security-acks.json"
	selectorOrderPath             = "/etc/404-probe-role-rehearsal/selector-order.json"
	installHelperPath             = "/usr/local/lib/404-probe-role-rehearsal/404-probe-install"
	agentConfigDirectory          = "/etc/404-probe-role-rehearsal"
	agentStateDirectory           = "/var/lib/404-probe-role-rehearsal"
	securityStateDirectory        = "/var/lib/404-probe-role-rehearsal-security"
	securityServiceUnitPath       = "/etc/systemd/system/404-probe-role-security-rehearsal.service"
	securityTimerUnitPath         = "/etc/systemd/system/404-probe-role-security-rehearsal.timer"
	removalStateDirectory         = "/var/lib/404-probe-role-rehearsal-updater/removal"
	removalRequestPath            = "/var/lib/404-probe-role-rehearsal-updater/removal/request.json"
	removalFinishedMarker         = "/var/lib/404-probe-role-rehearsal-updater/removal/agent-uninstalled"
	removalWorkerBinary           = "/usr/local/lib/404-probe-role-rehearsal/.404-probe-agent-removal-worker"
	removalWorkerUnitPath         = "/etc/systemd/system/404-probe-role-agent-removal-rehearsal.service"
	removalWorkerUnitName         = "404-probe-role-agent-removal-rehearsal.service"
	removalFinalizerUnitPath      = "/etc/systemd/system/404-probe-role-agent-removal-finalize-rehearsal.service"
	removalFinalizerUnitName      = "404-probe-role-agent-removal-finalize-rehearsal.service"
	removalHelperContract         = "REMOVAL_STATE_DIRECTORY"
	removalAccountHelperContract  = "finalize-agent-removal-account"
	removalWorkerWritablePaths    = "/var/lib/404-probe-role-rehearsal-updater /etc/systemd/system"
	removalFinalizerWritablePaths = "/etc /var/lib /run /usr/local/lib"
)
